package: 
  name: omniscient
  version: "0.0.8"

source:
  git_rev: v0.0.8
  git_url: https://github.com/samueljamesbader/Omniscient

requirements:
  build:
    - python >=3
    - setuptools
  run:
    - python >=3
    - numpy
    - pint

test:
  imports:
    - omniscient

about:
  home: https://github.com/samueljamesbader/Omniscient
  license: MIT
  license_file: LICENSE
