package: 
  name: omniscient
  version: "0.0.5"

source:
  git_rev: v0.0.5
  git_url: https://github.com/samueljamesbader/Omniscient

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - pint

test:
  imports:
    - omniscient

about:
  home: https://github.com/samueljamesbader/Omniscient
  license: MIT
  license_file: LICENSE
